module.exports = {
    a11y: ['axe-webdriver'],
    analyze: ['sh:analyze'],
    continuous: ['sh:continuous'],
    deploy: [
        'sh:build',
        'sh:verify',
        'clean:source-maps',
        'replace:bundle',
        'copy:404',
        'replace:runtime',
        'clean:runtime',
        'copy:assets',
        'copy:scripts',
        'copy:styles',
        'replace:assets',
        'clean:assets',
        'replace:scripts',
        'clean:scripts',
        'replace:styles',
        'clean:styles',
        'replace:chunks',
        'replace:csp-production',
        'htmlmin',
        'replace:manifest',
        'gh-pages:deploy',
        'smoke'
    ],
    e2e: ['sh:e2e'],
    lint: ['postcss:lint', 'sh:lint-config', 'sh:lint-src', 'sh:lint-test'],
    monitor: ['sh:monitor'],
    preview: ['sh:preview'],
    smoke: ['sh:smoke'],
    test: ['sh:test']
};
